const $=s=>document.querySelector(s);let root=null,active=null,files=new Map(),dirty=new Set(),blocks=[{type:"print",text:"Hello from VoidCode"},{type:"wait",text:"1"}];
function log(s){$("#termout").textContent+=s+"\\n";$("#termout").scrollTop=$("#termout").scrollHeight}function tabs(){const t=$("#tabs");t.innerHTML="";files.forEach((v,p)=>{const x=document.createElement("div");x.className="tab"+(p===active?" active":"");x.textContent=p.split(/[\\\\/]/).pop()+(dirty.has(p)?" •":"");x.onclick=()=>openFile(p);t.append(x)})}function tree(items){$("#tree").innerHTML="";items.forEach(x=>{const d=document.createElement("div");d.className="node "+(x.dir?"folder":"file");d.textContent=(x.dir?"▸ ":"")+x.name;d.onclick=()=>x.dir?voidAPI.listDir(x.path).then(tree):openFile(x.path);$("#tree").append(d)})}
async function openFolder(){const p=await voidAPI.pickFolder();if(!p)return;root=p;$("#cwd")&&($("#cwd").textContent=p);$("#sideTitle").textContent=p.split(/[\\\\/]/).pop().toUpperCase();tree(await voidAPI.listDir(p))}
async function openFile(p){if(!files.has(p))files.set(p,await voidAPI.readFile(p));active=p;$("#editor").value=files.get(p);$("#crumb").textContent=p;tabs();gutter();$("#editor").focus()}
async function save(){if(!active)return;files.set(active,$("#editor").value);await voidAPI.writeFile(active,files.get(active));dirty.delete(active);tabs();log("Saved "+active)}
async function newFile(){if(!root)return openFolder();let n=0,p;do{p=root+"\\\\untitled"+(n?n:"")+".js";n++}while(files.has(p));files.set(p,"");active=p;dirty.add(p);$("#editor").value="";tabs();gutter()}
async function run(){if(active)await save();if(!root)return log("Open a project first.");const c=$("#runCommand").value.trim()||"npm start";log("$ "+c);const r=await voidAPI.shell(c,root);log(r.output||"Process exited "+r.code)}
async function build(){if(active)await save();if(!root)return log("Open a project first.");const d={exe:"npm run dist",plugin:"npm run build",html:"npm run build",js:"npm run build",java:"gradlew build",python:"python -m PyInstaller --onefile main.py",rust:"cargo build --release",custom:""};const c=$("#buildCommand").value.trim()||d[$("#target").value];log("Building "+$("#target").value+"...");const r=await voidAPI.shell(c,root);$("#outputText").textContent=r.output||("Build finished with code "+r.code);log(r.output||("Build finished with code "+r.code))}
function gutter(){const n=$("#editor").value.split("\\n").length;$("#gutter").innerHTML=Array.from({length:n},(_,i)=>i+1).join("<br>")}
function visual(){const box=$("#blocks");box.innerHTML="";blocks.forEach((b,i)=>{const d=document.createElement("div");d.className="block";const s=document.createElement("select");["print","wait","if","loop"].forEach(t=>{const o=document.createElement("option");o.value=t;o.textContent=t.toUpperCase();if(t===b.type)o.selected=true;s.append(o)});const inp=document.createElement("input");inp.value=b.text;s.onchange=()=>{b.type=s.value;visual()};inp.oninput=()=>b.text=inp.value;d.append(s,inp);box.append(d)})}
function generate(){const js=blocks.map(b=>b.type==="print"?"console.log("+JSON.stringify(b.text)+");":b.type==="wait"?"await new Promise(r=>setTimeout(r,"+(Number(b.text)||1)+"*1000));":b.type==="if"?"if ("+b.text+") {}":"for(let i=0;i<"+(Number(b.text)||1)+";i++) {}").join("\\n");$("#codeView").classList.remove("hidden");$("#visualView").classList.add("hidden");if(!active&&root){active=root+"\\\\visual-generated.js";files.set(active,js);dirty.add(active)}else if(active){files.set(active,js);dirty.add(active)}$("#editor").value=js;tabs();gutter();log("Generated JavaScript from visual blocks.")}
$("#folderBtn").onclick=openFolder;$("#openBtn").onclick=()=>voidAPI.pickFile().then(p=>p&&openFile(p));$("#saveBtn").onclick=save;$("#newBtn").onclick=newFile;$("#runBtn").onclick=run;$("#buildBtn").onclick=build;$("#visualBtn").onclick=()=>{$("#codeView").classList.add("hidden");$("#visualView").classList.remove("hidden");visual()};$("#addBlock").onclick=()=>{blocks.push({type:"print",text:"New block"});visual()};$("#generateCode").onclick=generate;$("#themeBtn").onclick=()=>document.body.classList.toggle("light");$("#settingsBtn").onclick=()=>$("#settings").classList.remove("hidden");$("#settingsSide").onclick=()=>$("#settings").classList.remove("hidden");$("#closeSettings").onclick=()=>$("#settings").classList.add("hidden");$("#closeWizard").onclick=()=>$("#wizard").classList.add("hidden");$("#projectBtn").onclick=()=>$("#wizard").classList.remove("hidden");
$("#createProject").onclick=async()=>{if(!root)return openFolder();const n=$("#projectName").value.trim()||"MyProject",type=$("#projectType").value,base=root+"\\\\"+n;const ext=type==="Java"?".java":type==="Python"?".py":type==="Rust"?".rs":type==="Roblox Plugin"||type==="Minecraft Plugin"?".txt":".js";const text=type==="HTML / CSS / JS"?"<!doctype html><html><body><h1>"+n+"</h1></body></html>":type==="Java"?"public class Main { public static void main(String[] args){ System.out.println(\\\"Hello\\\"); } }":type==="Python"?"print(\\\"Hello from "+n+"\\\")":type==="Rust"?"fn main(){println!(\\\"Hello from "+n+"\\\");}":"console.log(\\\"Hello from "+n+"\\\");";await voidAPI.writeFile(base+"\\\\"+(type==="HTML / CSS / JS"?"index.html":"main"+ext),text);log("Created "+type+" starter in "+base);$("#wizard").classList.add("hidden")};
$("#saveSettings").onclick=()=>{document.body.style.setProperty("--accent",$("#accent").value);$("#editor").style.fontSize=$("#fontSize").value+"px";$("#editor").style.whiteSpace=$("#wrap").value==="On"?"pre-wrap":"pre";document.body.classList.toggle("compact",$("#density").value==="Compact");document.body.classList.toggle("light",$("#theme").value==="Light");$("#settings").classList.add("hidden");localStorage.voidSettings=JSON.stringify({accent:$("#accent").value,font:$("#fontSize").value,density:$("#density").value,theme:$("#theme").value,wrap:$("#wrap").value})};
$("#updateBtn").onclick=()=>{log("VoidCode checks GitHub Releases for newer versions. Install the newest release to update.");$("#version").textContent="Update-ready";};
$("#editor").addEventListener("input",()=>{if(active){files.set(active,$("#editor").value);dirty.add(active);tabs()}gutter()});$("#editor").addEventListener("keydown",e=>{if(e.ctrlKey&&e.key==="s"){e.preventDefault();save()}if(e.key==="Tab"){e.preventDefault();document.execCommand("insertText",false,"    ")}});
document.querySelectorAll(".bt").forEach(b=>b.onclick=()=>{document.querySelectorAll(".bt").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.querySelectorAll(".panel").forEach(x=>x.classList.add("hidden"));$("#"+b.dataset.panel).classList.remove("hidden")});voidAPI.onTerminal(d=>$("#termout").textContent+=d);gutter();visual();